import { readFileSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

const read = (relativePath: string) => readFileSync(path.join(process.cwd(), relativePath), 'utf8')

describe('campus guide bridge contract', () => {
  it('wires campus-guide proxy through vite dev server and tauri bridge', () => {
    const vite = read('vite.config.ts')
    const bridge = read('src-tauri/src/http_server.rs')
    const shell = read('src/features/campus-guide/views/CampusGuideShell.vue')
    const home = read('src/features/campus-guide/views/CampusGuideHome.vue')
    const app = read('src/App.vue')

    expect(vite).toContain("'/campus-guide'")
    expect(vite).toContain("target: 'http://127.0.0.1:4399'")
    expect(bridge).toContain('.route("/campus-guide/*path", any(campus_guide_proxy))')
    expect(bridge).toContain('const CAMPUS_GUIDE_TARGET_BASE: &str = "https://wisdomscenic.map.qq.com";')
    expect(bridge).toContain('campus_guide_compute_sign')
    expect(bridge).toContain('/campus-guide-debug/probe')
    expect(bridge).toContain('/campus-guide-debug/field-matrix')
    expect(vite).toContain("'/campus-guide-debug'")
    expect(app).toContain('CampusGuideShell.vue')
    expect(shell).toContain('CampusGuideSearch')
    expect(shell).toContain('CampusGuideWalkLine')
    expect(shell).toContain('CampusGuidePoiDetail')
    expect(shell).toContain('CampusGuideRouteList')
    expect(shell).toContain('CampusGuideRouteMap')
    expect(shell).toContain('CampusGuideBus')
    expect(shell).toContain('CampusGuideActivity')
    expect(shell).toContain('CampusGuideNoticeList')
    expect(shell).toContain('CampusGuideAbout')
    expect(shell).toContain('CampusGuideCollect')
    expect(shell).toContain('CampusGuideMockLocation')
    expect(shell).toContain('CampusGuideYunyouIntro')
    expect(shell).toContain('CampusGuideYunyouDetail')
    expect(shell).toContain('CampusGuidePunchHome')
    expect(shell).toContain('CampusGuidePunchMap')
    expect(shell).toContain('CampusGuideHub')
    expect(shell).toContain('CampusGuideSettings')
    const dodge = read('src/features/campus-guide/map/marker-dodge.ts')
    expect(dodge).toContain('applyMarkerDodge')
    const offline = read('src/features/campus-guide/services/offline-cache.ts')
    expect(offline).toContain('writeSpotsCache')
    const phase2Endpoints = read('src/features/campus-guide/api/phase2-endpoints.ts')
    expect(phase2Endpoints).toContain("cardList: '/hbut/card/list'")
    expect(phase2Endpoints).toContain("shirtInfo: '/hbut/shirt/info'")
    expect(home).toContain('PoiCard')
    expect(home).toContain('EntranceMenu')
    expect(home).toContain('NoticeBar')
    expect(home).toContain('openYunyou')
    expect(home).toContain('openPunch')
    // #369：手绘层重试 + POI 暗色/安全区
    const core = read('src/features/campus-guide/map/campus-map-core.ts')
    expect(core).toContain('mountCustomLayer')
    expect(core).toContain('scheduleCustomLayerRetry')
    expect(core).toContain('pushDebugLog')
    expect(core).toContain("features: ['base']")
    const theme = read('src/features/campus-guide/map/map-theme.css')
    expect(theme).toContain('--app-safe-bottom')
    expect(theme).toContain("html[data-theme='graphite_night'] .campus-poi-card")
    expect(theme).toContain('html.dark .campus-poi-head h3')
  })

  it('resolves campus-guide API base: iOS/desktop loopback, Android without 127.0.0.1', () => {
    const config = read('src/features/campus-guide/config.ts')
    const client = read('src/features/campus-guide/api/wisdom_client.ts')

    expect(config).toContain("localBridgeBaseUrl: 'http://127.0.0.1:4399/campus-guide'")
    expect(config).toContain('resolveCampusGuideBaseUrl')
    expect(config).toContain('isLikelyAndroidUserAgent')
    expect(config).toContain('VITE_CAMPUS_GUIDE_HTTPS_BASE')
    // Android must not use loopback
    expect(config).toMatch(/isLikelyAndroidUserAgent\(\)[\s\S]*?return CAMPUS_GUIDE_CONFIG\.apiBase/)
    expect(client).toContain('resolveCampusGuideBaseUrl')
    expect(client).not.toContain('CAMPUS_GUIDE_CONFIG.apiBase.replace')
  })
})