use serde_json::json;

pub const QXZKB_QUERY_FIELDS: &str = "xnxq,kcmc,kcxz,ksxs,kclb,ksfs,type,xqmc,kkyxmc,kkjysmc,jxbmc,jxbzc,bjrs,source,skjs,sksjdd,schooltime,zdskrnrs,skdd,zongxs,llxs,syxs,shangjxs,shijianxs,";

pub fn qxzkb_options() -> serde_json::Value {
    json!({
        "success": true,
        "options": {
            "xnxq": [
                {"value": "2025-2026-2", "label": "当前学期"},
                {"value": "2025-2026-1", "label": "2025-2026-1"},
                {"value": "2024-2025-2", "label": "2024-2025-2"},
                {"value": "2024-2025-1", "label": "2024-2025-1"},
                {"value": "2023-2024-2", "label": "2023-2024-2"},
                {"value": "2023-2024-1", "label": "2023-2024-1"},
                {"value": "2022-2023-2", "label": "2022-2023-2"},
                {"value": "2022-2023-1", "label": "2022-2023-1"},
                {"value": "2021-2022-2", "label": "2021-2022-2"},
                {"value": "2021-2022-1", "label": "2021-2022-1"}
            ],
            "xqid": [
                {"value": "", "label": "请选择"},
                {"value": "1", "label": "本部"}
            ],
            "nj": [
                {"value": "", "label": "请选择"},
                {"value": "2031", "label": "2031"},
                {"value": "2030", "label": "2030"},
                {"value": "2029", "label": "2029"},
                {"value": "2028", "label": "2028"},
                {"value": "2027", "label": "2027"},
                {"value": "2026", "label": "2026"},
                {"value": "2025", "label": "2025"},
                {"value": "2024", "label": "2024"},
                {"value": "2023", "label": "2023"},
                {"value": "2022", "label": "2022"},
                {"value": "2021", "label": "2021"},
                {"value": "2020", "label": "2020"},
                {"value": "2019", "label": "2019"},
                {"value": "2018", "label": "2018"},
                {"value": "2017", "label": "2017"},
                {"value": "2016", "label": "2016"},
                {"value": "2015", "label": "2015"},
                {"value": "2014", "label": "2014"},
                {"value": "2013", "label": "2013"},
                {"value": "2012", "label": "2012"},
                {"value": "2011", "label": "2011"},
                {"value": "2010", "label": "2010"},
                {"value": "2009", "label": "2009"}
            ],
            "yxid": [
                {"value": "", "label": "请选择"},
                {"value": "113", "label": "教务处"},
                {"value": "115", "label": "党委研究生工作部、研究生院"},
                {"value": "201", "label": "机械工程学院"},
                {"value": "202", "label": "电气与电子工程学院"},
                {"value": "206", "label": "计算机科学与人工智能学院"},
                {"value": "203", "label": "材料与化学工程学院"},
                {"value": "204", "label": "生命科学与健康工程学院"},
                {"value": "205", "label": "土木建筑与环境学院"},
                {"value": "207", "label": "艺术设计学院"},
                {"value": "209", "label": "经济与管理学院"},
                {"value": "211", "label": "外国语学院"},
                {"value": "212", "label": "理学院"},
                {"value": "213", "label": "体育学院"},
                {"value": "208", "label": "工业设计学院"},
                {"value": "214", "label": "职业技术师范学院"},
                {"value": "215", "label": "国际学院"},
                {"value": "313", "label": "数字艺术产业学院"},
                {"value": "217", "label": "底特律绿色工业学院"},
                {"value": "302", "label": "继续教育学院"},
                {"value": "db5362d5239f4648bd3fb25abfa3e3bf", "label": "微专业"}
            ],
            "zyid": [
                {"value": "", "label": "请选择"}
            ],
            "kkyxid": [
                {"value": "", "label": "请选择"},
                {"value": "104", "label": "党委宣传部"},
                {"value": "110", "label": "团委"},
                {"value": "112", "label": "学科建设办公室"},
                {"value": "113", "label": "教务处"},
                {"value": "115", "label": "党委研究生工作部、研究生院"},
                {"value": "116", "label": "人事处"},
                {"value": "119", "label": "招生与就业指导处"},
                {"value": "120", "label": "实验室与资产管理处"},
                {"value": "121", "label": "国际交流与合作处"},
                {"value": "108", "label": "保卫部（处）"},
                {"value": "123", "label": "离退休工作处"},
                {"value": "105", "label": "党委统战部"},
                {"value": "201", "label": "机械工程学院"},
                {"value": "202", "label": "电气与电子工程学院"},
                {"value": "206", "label": "计算机科学与人工智能学院"},
                {"value": "203", "label": "材料与化学工程学院"},
                {"value": "204", "label": "生命科学与健康工程学院"},
                {"value": "205", "label": "土木建筑与环境学院"},
                {"value": "207", "label": "艺术设计学院"},
                {"value": "209", "label": "经济与管理学院"},
                {"value": "211", "label": "外国语学院"},
                {"value": "212", "label": "理学院"},
                {"value": "210", "label": "马克思主义学院"},
                {"value": "213", "label": "体育学院"},
                {"value": "208", "label": "工业设计学院"},
                {"value": "214", "label": "职业技术师范学院"},
                {"value": "215", "label": "国际学院"},
                {"value": "313", "label": "数字艺术产业学院"},
                {"value": "217", "label": "底特律绿色工业学院"},
                {"value": "302", "label": "继续教育学院"},
                {"value": "301", "label": "图书馆"},
                {"value": "304", "label": "档案馆"},
                {"value": "311", "label": "机电研究设计院（湖北省机电研究设计有限责任公司）"},
                {"value": "db5362d5239f4648bd3fb25abfa3e3bf", "label": "微专业"},
                {"value": "107", "label": "学生工作部（处）、武装部"},
                {"value": "98", "label": "创新创业学院"}
            ],
            "kkjysid": [
                {"value": "", "label": "请选择"}
            ],
            "kcxz": [
                {"value": "", "label": "请选择"},
                {"value": "16", "label": "限定性选修课"},
                {"value": "45", "label": "专业选修课"},
                {"value": "50", "label": "基础实践"},
                {"value": "51", "label": "专业实践"},
                {"value": "52", "label": "综合实践"},
                {"value": "53", "label": "其他实践"},
                {"value": "54", "label": "短学期实践"},
                {"value": "70", "label": "辅修双学位理论"},
                {"value": "71", "label": "辅修双学位实践"},
                {"value": "99", "label": "公共选修课"},
                {"value": "41", "label": "专业方向组选课"},
                {"value": "42", "label": "专业任选课"},
                {"value": "43", "label": "专业基础课"},
                {"value": "44", "label": "专业必修课"},
                {"value": "11", "label": "通识教育必修课"},
                {"value": "12", "label": "通识教育选修课"},
                {"value": "31", "label": "学科基础课"},
                {"value": "40", "label": "专业核心课"},
                {"value": "98", "label": "重修课"},
                {"value": "32", "label": "工程基础课"}
            ],
            "kclb": [
                {"value": "", "label": "请选择"},
                {"value": "05", "label": "通识教育必修课"},
                {"value": "06", "label": "学科基础类必修课"},
                {"value": "07", "label": "专业基础课"},
                {"value": "08", "label": "专业必修课"},
                {"value": "09", "label": "专业选修课"},
                {"value": "10", "label": "通识教育选修课"},
                {"value": "11", "label": "基础实践"},
                {"value": "12", "label": "专业实践"},
                {"value": "13", "label": "综合实践"},
                {"value": "14", "label": "限定性选修课"}
            ],
            "xslx": [
                {"value": "", "label": "请选择"},
                {"value": "1", "label": "理论"},
                {"value": "2", "label": "实验"},
                {"value": "3", "label": "上机"},
                {"value": "4", "label": "实践"},
                {"value": "5", "label": "环节"},
                {"value": "6", "label": "公选"},
                {"value": "7", "label": "自修"},
                {"value": "9", "label": "分级"},
                {"value": "10", "label": "其他"},
                {"value": "15", "label": "辅修"}
            ],
            "jxlid": [
                {"value": "", "label": "请选择"},
                {"value": "9", "label": "1教"},
                {"value": "16", "label": "2教"},
                {"value": "24", "label": "3教"},
                {"value": "1", "label": "4教"},
                {"value": "14", "label": "5教"},
                {"value": "23", "label": "6教实训楼"},
                {"value": "17", "label": "7教"},
                {"value": "18", "label": "北教1"},
                {"value": "5", "label": "北教2"},
                {"value": "bqtyndl", "label": "北区太阳能大楼"},
                {"value": "bqwqg", "label": "北区网球馆"},
                {"value": "6", "label": "创业园"},
                {"value": "2", "label": "工1"},
                {"value": "25", "label": "工2"},
                {"value": "10", "label": "机电楼"},
                {"value": "7", "label": "金工楼"},
                {"value": "3", "label": "金工实习楼"},
                {"value": "19", "label": "科技楼"},
                {"value": "8", "label": "酿造楼"},
                {"value": "20", "label": "农机楼"},
                {"value": "21", "label": "轻工楼"},
                {"value": "11", "label": "生化楼"},
                {"value": "27", "label": "实训中心"},
                {"value": "sc001", "label": "双创大楼"},
                {"value": "scdl", "label": "双创大楼A座"},
                {"value": "26", "label": "图书馆"},
                {"value": "12", "label": "土建楼"},
                {"value": "000", "label": "无楼栋"},
                {"value": "99", "label": "无楼号"},
                {"value": "22", "label": "运动场所"},
                {"value": "28", "label": "资环二"},
                {"value": "13", "label": "资环楼"},
                {"value": "30", "label": "资环三"},
                {"value": "29", "label": "资环一"}
            ],
            "jslx": [
                {"value": "", "label": "请选择"},
                {"value": "05", "label": "多媒体"},
                {"value": "04", "label": "语音室"},
                {"value": "03", "label": "实验室"},
                {"value": "09", "label": "网络教室"},
                {"value": "10", "label": "练功房"},
                {"value": "14", "label": "体育教室"},
                {"value": "11", "label": "基础实验室"},
                {"value": "12", "label": "专业实验室"},
                {"value": "15", "label": "工图教室"},
                {"value": "16", "label": "智慧多媒体"},
                {"value": "17", "label": "画室"},
                {"value": "18", "label": "操场"},
                {"value": "19", "label": "多媒体（创）"},
                {"value": "99", "label": "无教室类型"}
            ],
            "ksxs": [
                {"value": "", "label": "请选择"},
                {"value": "2", "label": "考查"},
                {"value": "1", "label": "考试"},
                {"value": "11", "label": "一类考试"},
                {"value": "22", "label": "二类考试"},
                {"value": "333", "label": "三类考试"}
            ],
            "ksfs": [
                {"value": "", "label": "请选择"},
                {"value": "1", "label": "笔试"},
                {"value": "5", "label": "机考"},
                {"value": "8", "label": "非机考"}
            ],
            "zxxq": [
                {"value": "", "label": "请选择"},
                {"value": "7", "label": "星期日"},
                {"value": "1", "label": "星期一"},
                {"value": "2", "label": "星期二"},
                {"value": "3", "label": "星期三"},
                {"value": "4", "label": "星期四"},
                {"value": "5", "label": "星期五"},
                {"value": "6", "label": "星期六"},
                {"value": "7", "label": "星期日"}
            ],
            "zdxq": [
                {"value": "", "label": "请选择"},
                {"value": "7", "label": "星期日"},
                {"value": "1", "label": "星期一"},
                {"value": "2", "label": "星期二"},
                {"value": "3", "label": "星期三"},
                {"value": "4", "label": "星期四"},
                {"value": "5", "label": "星期五"},
                {"value": "6", "label": "星期六"},
                {"value": "7", "label": "星期日"}
            ],
            "xsqbkb": [
                {"value": "1", "label": "是"},
                {"value": "0", "label": "否"}
            ],
            "kklx": [
                {"value": "", "label": "请选择"},
                {"value": "1", "label": "主修开课"},
                {"value": "18", "label": "补修开课"},
                {"value": "2", "label": "公选课开课"},
                {"value": "3", "label": "分级教学"},
                {"value": "5", "label": "重修选课"},
                {"value": "22", "label": "微专业开课"}
            ]
        },
        "defaults": {
            "xnxq": "2025-2026-2",
            "xsqbkb": "0",
            "kklx": ["1", "18", "2", "3", "5", "22"]
        }
    })
}
